### ISSUE TITLE
Create a file with your user handle and write what your learning interests are

### ISSUE THREAD

**Issue by nbkhope** [nbktechworld/introduction-to-git2#2]
For example:

nbkhope.txt
```
I'm interested in Git and GitHub
```

**Comment by nbkhope** [comment]
Hey, I don't understand exactly what you mean by X. Could you elaborate? cc @person-name

**Comment by nbkhope** [comment]
Hey, I meant it to be like this and that. Ok?

**Comment by Azeem-Cole** [comment]
Hey,  i like would to contribute!

**Comment by DarklingKore** [comment]
Hey, I would like to contribute!

**Comment by coxco96** [comment]
Hey, I'd also like to contribute!
